export default [
       
        // [
        //     "rahul.sahu.ug21@nsut.ac.in",
        //     "Shatranj",
        //     "nsitchessclub@gmail.com",
        //     "MOKSHA",
        //     "CrazyHouse",
        //     "\"CrazyHouse Chess: Where Strategy Takes Flight and Madness Rules the Board!\"",
        //     "The initial setup follows standard chess rules.\n\nPiece Drops:\nCaptured pieces are not removed from the game but instead become part of the capturing player's reserve.\nOn a turn, a player can either make a standard chess move or drop a piece from their reserve onto an empty square.\n\nPawn Drops:\nPawns cannot be dropped on the first or eighth rank.\nPawns dropped on the seventh rank promote to the piece of the player's choice.\n\nCheck and Checkmate:\nThe standard rules of check and checkmate apply.\nA player must make a move that gets their king out of check if it is under threat.\n\nStalemate:\nStalemate is a draw. A player with no legal moves and not in check is considered stalemated.\n\nResignation:\nPlayers may resign at any time, conceding the game to their opponent.\n\nTime Control:\nThe event may have a time control system, specifying the amount of time each player has to make their moves.\n\nDraw Conditions:\nThe event may have specific rules regarding draw conditions, such as threefold repetition or the fifty-move rule.\n\nFair Play:\nPlayers are expected to play fairly and follow the rules of the game.\nCheating, using chess engines, or receiving external assistance is strictly prohibited.",
        //     "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1cw8hGzXP8rBs1kUqSZshAMFSBgPtI8Qn.png",
        //     "Anubhav K",
        //     "+91 73008 40935",
        //     "Paras Dalal",
        //     "+91 87449 90244",
        //     "",
        //     null
        // ],
        // [
        //     "rahul.sahu.ug21@nsut.ac.in",
        //     "Shatranj",
        //     "nsitchessclub@gmail.com",
        //     "MOKSHA",
        //     "Simulateous Exhibition",
        //     "\"Simul Mastery: Challenge the Grandmaster Within You in our Simultaneous Chess Exhibition!\"",
        //     "Simultaneous chess, often referred to as a simul, is an engaging format where a single player (typically a master) takes on multiple opponents at the same time. The rules and regulations for a simul variant are designed to ensure a fair and enjoyable experience for both the master and the participants. Here are the common rules:\n\nNumber of Opponents:\nThe master should specify the maximum number of opponents they are willing to play against in the simul.\n\nClocks:\nA chess clock may be used to manage time. The master typically has an overall time limit for all games combined.\n\nBoard Setup:\nThe master makes the first move on each board, and the games progress from there.\n\nRotation:\nThe master rotates through the boards in a predetermined order, making one move at a time on each board.\n\nMove Order:\nThe order of moves may follow a sequential rotation or be determined by the master based on the current position of each board.\n\nChallenges:\nParticipants can challenge the master during the simul by making moves in the hope of securing an advantage or a draw.\n\nScoring:\nPoints may be awarded based on the outcome of each individual game (e.g., 1 point for a win, 0.5 for a draw, and 0 for a loss).\n\nEnd of Game:\nGames continue until all have concluded or until a predetermined time limit is reached.\n\nSimultaneous Win/Loss:\nThe master can win or lose individual games independently, and the overall result is calculated based on the accumulated points.\n\nResignation:\nParticipants can resign individual games if they believe they are in a losing position.\n\nEtiquette:\nPlayers are expected to follow standard chess etiquette and not disturb other participants during the simul.\n\nFair Play:\nParticipants are expected to play fairly and not seek external assistance.\nArbitration:\n\nAn arbiter may be present to resolve disputes and ensure fair play.",
        //     "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1XrTXa1HETtIBpwUYV-58rdddlZHAOjZV.png",
        //     "Anubhav K",
        //     "+91 73008 40935",
        //     "Paras Dalal",
        //     "+91 87449 90244",
        //     "",
        //     null
        // ],
        [
            "divyam.singh.ug21@nsut.ac.in",
            "Clitch",
            "clitch.nsut1@gmail.com",
            "MOKSHA",
            "Rouge",
            "The Fashion Show ",
            "Their will be a preliminary round before the final performance, dates will be informed later. \n\nThose who clear the preliminary round will be performing on the main stage in the finals.\n\nThe Maximum size of the team is 14 members including makeup artists and stage helpers \n(The performing models should be minimum 8 and maximum 10). No stage help will be provided by the team \n\nThe minimum time limit for act is 7 and maximum time is 10 minutes \n\nParticipants must report backstage on time otherwise they will be disqualified \n\nParticipants are requested to carry their own makeup, mirrors, costumes, props, and anything else that they may require for preparations and performance. Organizers will not be providing participants any of these things. Each participant is responsible for the safety of their belongings.\n\nParticipants should not carry with them cigarettes, alcohol, e-cigarettes, or any other illegal substances. This will lead to disqualification.\n\nWith all the creative liberty given to the participants, however, they need to be original costumes and designs. Plagiarism of any kind would lead to disqualification. The final look should not be obscene or\ninappropriate in any manner.\n\nAny unfair practices would lead to immediate disqualification of the team.\n\nThe decision of the judges will be final and binding.\n\nParticipants will get no more than 45 minutes in the greenroom before their performance, and will get 20 minutes in the greenroom after their performance to wrap up. Participants are requested to strictly adhere to these timelines, any extension will not be tolerated.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1uM4YhaeaHN4m96psLZLhZERJpY-aG-p5.png",
            "Lalit ",
            "8178634241",
            "Chhavi ",
            "9560603540",
            "Name of College,Name of Society ,POC 1 Name,\nPOC 1 Contact ,POC 2 Name,\nPOC 2 Contact ,Size of Team ,\nMember 4 Name ,Member 5 Name ,\nMember 6 Name ,Member 7 Name ,\nMember 8 Name ,Member 9 Name ,\nMember 10 Name ,Member 11 Name ,\n<Member 12 Name, Member 13 Name,\nMember 14 Name >",
            "Lifestyle "
        ],
        [
            "mohit.parbat.ug21@nsut.ac.in",
            "ASME",
            "asme@nsut.ac.in",
            "INNOVISION",
            "Beyond The Grid",
            "reviving the past, Designing the future: A 3D design competition to reimagine nostalgia!",
            "Every participant should follow the listed rules and any discrepancy may result in disqualification from the event.\n\n1) All participants must reach the venue on time .\n\n2) participants should carry their laptops with them. \n\n3) participants can use any standard CAD software of their choice.\n\n4) participants must make sure that submitted work is not a copy of any other project, the design has to be the original pieces of work and it should not infringe on any existing intellectual property right.\n\n5) participants must submit their designs within the given time frame (Important).\n\n6) Participants should maintain a healthy competitive environment throughout the event.\n\n7) All the submitted 3D designs  and models will become the property of ASME and can be used as a promotional purposes.\n\n8) Fair play and ethical conduct are expected throughout the competition.\n0",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1F_zLI3fxtQimyAIMQShhUIxMfgBtzeLG.png",
            "Mohit",
            "9810531582",
            "Utkarsh",
            "8076060624",
            "First Name,Last Name,\nRoll Number,Age,\nPhone Number,E-mail ID,\nUniversity Name,\nBranch,Year\n",
            "Innovision "
        ],
        [
            "ishita_srivastava.ug22@nsut.ac.in",
            "Ashwamedh Street",
            "ashwamedh.street@gmail.com",
            "MOKSHA",
            "Ekaanki",
            "The Street Play Event",
            "Round 1 (Prelims)\n\n1. The preliminary round will be held in NSUT campus\n2. A play is to be performed of maximum \"8+2\" minutes duration.\n3. The maximum number of team members allowed is 25.\n4. Please bring along your identity cards.\n5. Teams are required to bring printouts of their team lists.\n\nRound 2 (Finals):\n\n1. Performance should not exceed “18+2” minutes in length(Empty circle to Empty circle).\n2. Teams are allowed to use musical props such as Dholak, Flute or any other musical instrument of their choice, but usage of microphones or other electrical instruments is not allowed.\n3. No instruments will be provided by NSUT. So teams are required to bring their own instruments.\n4. Use of fire, water, powder or any hazardous element/prop is strictly prohibited.\n5. Obscenity of any kind that is harmful to the interests or beliefs of specific but not limited to social, economic, religious, gender or political groups will lead to the disqualification of the team.\n6. Performance must be suitable for the general audience and should not contain any offensive or inappropriate content.\n7. We highly discourage any plagiarism in the event. Any team copying a play without any prior permission of the play writer will be disqualified.\n8. The decision of the judging panel will be final and binding\n",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1y_tX9oKlPPiMJRvBz3WVokRbhx0n4bH8.png",
            "Vibhuti Minghlani",
            "8448107298",
            "Abishek",
            "9810930618",
            "Name of the College , Name of the Society,\nEmail ID (society),Name of POC 1 ,Contact of POC 1,Name of POC 2 ,Contact of POC 2,Name of the Play,Synopsis of the Play (drive link),Team List (drive link)",
            "Theatre "
        ],
        [
            "ishita_srivastava.ug22@nsut.ac.in",
            "Ashwamedh Street",
            "ashwamedh.street@gmail.com",
            "MOKSHA",
            "Ekaanki",
            "The Monoact Competition",
            "Preliminary Round\n\n1. Time limit: 2-3 minutes\n2. Submit the drive link of the video before given deadline.\n\nFinal Round\n1. Time limit: 5-7 minutes.\n2. Participants must arrange their own costumes, props and lighting.\n3. Language: English, Hindi or both.\n4. Music (if any): Bring it on a pen-drive or notify for live beats beforehand \n5. Obscenity of any kind that is harmful to the interests or beliefs of specific but not limited to social, economic, religious, gender or political groups will lead to the disqualification of the participant.\n6. We highly discourage any plagiarism in the event. \n7. Judges' decisions are final and binding ",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1EgmNEwftLgABdrpmA2HvEIuRnlCUDb0Y.png",
            "Ishita",
            "9810352746",
            "Kanupriya",
            "9772212002",
            "Name of the College ,Participant Name,Contact Number,Email ID\n,Prelims video submission (drive link)\n",
            "Theatre "
        ],
        [
            "ishita_srivastava.ug22@nsut.ac.in",
            "Ashwamedh Street",
            "ashwamedh.street@gmail.com",
            "MOKSHA",
            "Chalchitra",
            "The 50-Hour Filmmaking Competition.",
            "1. 50 hours will be given to the teams and they are required to shoot, edit and send their final submission within the duration.\n\n2. A theme will be provided to the team leader on their Email-ID at the commencement of the 50 hour duration.\n\n3. Participants need to submit their film at ashwamedh.street@gmail.com from their registered Email-ID with the “TeamName_Title”.\n\n4. Language of the film can be English, Hindi or both.\n\n5. The finished film must be a minimum of 4 minutes in duration, and a maximum of 6 minutes —not including end credits.\n\n6. Teams cannot use stock footage or footage created earlier. Photographs can be used in a film, only if the team has the rights to use them.\n\n7. The final video must be uploaded in MP4/MOV/MPEG-4 format. The uploaded video should be in 1080p and strictly below 2 GB.\n\n8. The decision of the judges will be final and binding.\n",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1stgM3kxY_XOJ2UTktzcz1FFlIXdRuSyM.png",
            "Abhijeet",
            "8340546184",
            "Aakash",
            "8076963660",
            "Name of the College,Team Name,Name of Team Leader,Contact of Team Leader,Email ID of Team Leader",
            "Theatre "
        ],
        [
            "palkin.gupta.ug21@nsut.ac.in",
            "Capella",
            "capellansut1@gmail.com",
            "MOKSHA",
            "Mudra",
            "weaving stories with every move?",
            "1. Team limit: 17 + 3 (performing + infra members)\n2. Time Limit: 4-6 minutes including relevant voice-overs and 1 minute for setup. \n3. The soundtrack should be only instrumental (except the narrative part). All teams are requested to carry their soundtrack in a pen drive in mp3 format. \n4. The final tracks have to be submitted by 29th February 11:59PM on capellansut1@gmail.com with the timestamps of the voice-overs wherever used. \n5. The performance necessarily has to be thematic.\n6. Only contemporary and related dance forms are allowed.\n7.  Footwear won't be allowed on the stage during the performance.\n8.  The stage limit is 17. At any point more than 17 participants won't be allowed on the stage.\n9.  At Least 2 people should be on the stage at all times.\n10. Any kind of fluid, flame, powders, heavy or sharp objects are strictly prohibited. Teams need to specify beforehand if they will be using any kind of props.\n11. All the participants are required to show their ID cards.\n12. The Organizing Committee shall not provide any instruments/accompanists. The contestants should install/ test their tracks with the equipment available at the venue beforehand. No extra time shall be given during the time of the performance. \n13. In case the participants exceed the time limit, the judges will be free to disqualify the participating team.\n14. The Organizing Committee reserves the right to change the venue, time and rules if need be. \n15. The decision of judges will be final and binding.\n\nFinal\nRules and Regulations*  \n1. Team limit: 17 + 3 (performing + infra members)\n2. Time Limit: 8-10 minutes including relevant voice-overs and 2 minutes for setup. \n3. The soundtrack should be only instrumental (except the narrative part). All teams are requested to carry their soundtrack in a pen drive in mp3 format.\n4. The final tracks have to be submitted by 29th February 11:59PM on capellansut1@gmail.com with the timestamps of the voice-overs wherever used.\n5. The performance necessarily has to be thematic.\n6. Only contemporary and related dance forms are allowed.\n7.  Footwear won't be allowed on the stage during the performance.\n8.  The stage limit is 17. At any point more than 17 participants won't be allowed on the stage.\n9.  At Least 2 people should be on the stage at all times.\n10. Any kind of fluid, flame, powders, heavy or sharp objects are strictly prohibited. Teams need to specify beforehand if they will be using any kind of props.\n11. All the participants are required to show their ID cards.\n12. The Organizing Committee shall not provide any instruments/accompanists. The contestants should install/ test their tracks with the equipment available at the venue beforehand. No extra time shall be given during the time of the performance. \n13. In case the participants exceed the time limit, the judges will be free to disqualify the participating team.\n14. The Organizing Committee reserves the right to change the venue, time and rules if need be. \n15. The decision of judges will be final and binding",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1rSea3E3ByRvJlTFHOhrP-6j-KPL2-VpM.png",
            "Lakshya Ruhela",
            "7412959686",
            "Suhani Chaturvedi",
            "9873004283",
            "Team Name,\nTeam Leader,\nTeam Leader's Phone Number ,\nCollege Name ,\nContact Email,\nPerforming members ,\nInfra members ,Name of POC1,\nPhone number of POC1,\nName of POC2,Phone number of POC2,Team Leader's Name,\nTeam Leader's Phone Number ,Team Member 2,Contact Number, \nTeam Member 3,Contact Number,\nTeam Member 4*,Contact Number ,\nTeam Member 5*,Contact Number ,\nTeam Member 6*,Contact Number ,\nTeam Member 7*,Contact Number ,\nTeam Member 8*,Contact Number ,\nTeam Member 9*,Contact Number, \nTeam Member 10*,Contact Number ,*\nTeam Member 11*,Contact Number ,*\nTeam Member 12*,Contact Number ,*\nTeam Member 13*,Contact Number ,*\nTeam Member 14*,Contact Number ,*\nTeam Member 15*,Contact Number ,*\nTeam Member 16*,Contact Number ,*\nTeam Member 17*,Contact Number *,\nTeam Member 18*,Contact Number *,\nTeam Member 19*,Contact Number* ,\nTeam Member 20*,Contact Number* ",
            "Dance "
        ],
        [
            "palkin.gupta.ug21@nsut.ac.in",
            "Capella",
            "capellansut1@gmail.com",
            "MOKSHA",
            "Kalakriti",
            "Beats of Tradition",
            "1. Team limit: 20 + 5 (performing + infra members)\n2. Time Limit: 4-6 minutes including relevant voice-overs and 1 minute for setup. \n3. All teams are requested to carry their soundtrack in a pen drive in mp3 format. \n4. The final tracks have to be submitted by 29th February 11:59PM on capellansut1@gmail.com with the timestamps of the voice-overs wherever used. \n5. The performance necessarily has to be any traditional folk dance.\n6.  The stage limit is 17. At any point more than 17 participants won't be allowed on the stage.\n7.  At Least 2 people should be on the stage at all times.\n8. Any kind of fluid, flame, powders, heavy or sharp objects are strictly prohibited. Teams need to specify beforehand if they will be using any kind of props.\n9. All the participants are required to show their ID cards.\n10. The Organizing Committee shall not provide any instruments/accompanists. The contestants should install/ test their tracks with the equipment available at the venue beforehand. No extra time shall be given during the time of the performance. \n11. In case the participants exceed the time limit, the judges will be free to disqualify the participating team.\n12. The Organizing Committee reserves the right to change the venue, time and rules if need be. \n13. The decision of judges will be final and binding.\nFinal*\nRules and Regulations*  \n1. Team limit: 20 + 5 (performing + infra members)\n2. Time Limit: 8-10 minutes including relevant voice-overs and 2 minutes for setup. \n3. The soundtrack should be only instrumental (except the narrative part). All teams are requested to carry their soundtrack in a pen drive in mp3 format.\n4. The final tracks have to be submitted by 29th February 11:59PM on capellansut1@gmail.com with the timestamps of the voice-overs wherever used.\n5. The performance necessarily has to be any traditional folk dance.\n6.  The stage limit is 17. At any point more than 17 participants won't be allowed on the stage.\n7.  At Least 2 people should be on the stage at all times.\n8. Any kind of fluid, flame, powders, heavy or sharp objects are strictly prohibited. Teams need to specify beforehand if they will be using any kind of props.\n9. All the participants are required to show their ID cards.\n10. The Organizing Committee shall not provide any instruments/accompanists. The contestants should install/ test their tracks with the equipment available at the venue beforehand. No extra time shall be given during the time of the performance. \n11. In case the participants exceed the time limit, the judges will be free to disqualify the participating team.\n12. The Organizing Committee reserves the right to change the venue, time and rules if need be. \n13. The decision of judges will be final and binding.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1rQY2GvcU_rqVW12U4WhkHC-MkArnZh4I.png",
            "Kashish Goel",
            "8448179695",
            "Shivam Gupta",
            "9351820323",
            "Team Name,\nTeam Leader,\nTeam Leader's Phone Number ,\nCollege Name ,\nContact Email,\nPerforming members ,\nInfra members ,Name of POC1,\nPhone number of POC1,\nName of POC2,Phone number of POC2,Team Leader's Name,\nTeam Leader's Phone Number ,Team Member 2,Contact Number, \nTeam Member 3,Contact Number,\nTeam Member 4*,Contact Number ,\nTeam Member 5*,Contact Number ,\nTeam Member 6*,Contact Number ,\nTeam Member 7*,Contact Number ,\nTeam Member 8*,Contact Number ,\nTeam Member 9*,Contact Number, \nTeam Member 10*,Contact Number ,*\nTeam Member 11*,Contact Number ,*\nTeam Member 12*,Contact Number ,*\nTeam Member 13*,Contact Number ,*\nTeam Member 14*,Contact Number ,*\nTeam Member 15*,Contact Number ,*\nTeam Member 16*,Contact Number ,*\nTeam Member 17*,Contact Number *,\nTeam Member 18*,Contact Number *,\nTeam Member 19*,Contact Number* ,\nTeam Member 20*,Contact Number* ",
            "Dance "
        ],
       
        
        [
            "aarush.tripathi.bba21@nsut.ac.in",
            "Intaglios ",
            "intagliosthe@gmail.com",
            "MOKSHA",
            "MOKSHA GOT TALENT ",
            "Exhibiting one’s talent at the greatest platform !! ",
            "This event will be conducted in form of a competition between the participants. It comprises of 2 rounds.\nPair of two individuals can be allowed to participate. For eg:- A singer and an instrumentalist.\nIn the first round the participants need to record a video of their art, activity & performance and upload it in the form that will be made available to all. The video shouldn't exceed the time limit of 3 minutes. The deserving participants will be selected and shall qualify for round 2. \nRound 2 will conducted on the day of Moksha fest, at a suitable venue, in front of the judges and an audience. For round 2, every participant needs to give his/her best shot.Scored will be marked and their performances would be assessed by the judges.\nThe best performer will be crowned as winner.Winners will be ranked as per 1st, 2nd and 3rd position(s).",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1E-qr6lOARLJcAlgzuBXhATXxrUYrr95y.png",
            "Mrityunjay Gupta ",
            "93183 10099",
            "Nikhil Kumar ",
            "83779 49111",
            "Email, Your Name, College Name, Your Email-ID, Your preferred skill set {Dancing, Singing, Rapping, Instrumental Music, Others}, Drive link of your performance(drive link), Why you want to participate in MGT ?",
            "Literary"
        ],
        [
            "utkarsh.tripathy.ug21@nsut.ac.in",
            "SHAKESJEER",
            "shakesjeer.nsutd@gmail.com",
            "MOKSHA",
            "COMEDY HUNT",
            "The Stand Up Competition",
            "1) Team Size: Solo\n2) Judging Criteria: Content, Quality of humor, 3) Stage presence, Audience engagement, \n     Clarity of thought, Wackiness, USP (Unique \n      selling point)\n4)General Rules-\n  Mono -acting, puppetry, musicals are not \n  allowed though ventriloquism is allowed.\n  Use of props is allowed, brought in by the \n  participant himself. The organizers hold the \n  discretion of allowing it on stage.\n  Both English and Hindi are allowed. However \n  short sub passages in other regional \n  languages are allowed.\n  Decisions taken by the judge are absolute and \n  binding.\n  Use of obscenity/profanity (at the discretion \n  of the judges) is not allowed and there should \n  be no direct implications.\n  Any Form of music is not allowed during the \n  performance.\n  Since the participants are called upon in a \n  random order, everyone is required to be \n  present at least 5 minutes prior to the start.\n  Organizers will not be responsible if you are \n  unable to show up on time and miss your slot.\n\n\nPreliminary Round-\n  Time limit : 5 minutes\n  Participants have to submit the drive link of \n  the video before the given deadline.\n\n\nFinal Round-\n  Time limit : 5-7 min",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1Z5aQFkG0MHuqYnMFhNDdz7xg2zEAQQOl.png",
            "Vidhi",
            "8882969954",
            "Utkarsh",
            "9810366025",
            "Name of the College, Participant Name, Contact No., Email-ID, Prelims video submission (drive link)",
            "Theatre "
        ],
        [
            "vaishali.sharma.ug21@nsut.ac.in",
            "Ashwamedh stage",
            "ashwamedh2020@gmail.com",
            "MOKSHA",
            "parwaz",
            "inter-college stage play competition",
            "Rules and Regulations that should be adhered during the Prelim performance:\n1)Team size of maximum 20 people is allowed. \n2)All the participants are required to show their ID cards. \n3)Props that shall be required during the performance will not be provided by the organizing committee. \n4)Technical assistance shall be provided at the venue. \n5)The Organising Committee reserves the right to change the venue, time and rules, if the need be. \n6)The decision of the judges shall be final and binding. \n",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1jK4Ui7kfM03bA_1dRVQyzKNx5Blw8bNJ.png",
            "suryansh",
            "7011659441",
            "pravina",
            "78276 17802",
            "College Name, Team Name, Play Title, Writer Name, Director Name, Team Size(Including production and backstage), Email of the Society, POC 1 (name), POC 1 (contact), POC 2 (name), POC 2 (contact), [Team Details (Include Name, Email, Roll Number and Contact Number)], [Poster of Play], Synopsis of Play(max 250 words)",
            "Theatre "
        ],
        [
            "vaishali.sharma.ug21@nsut.ac.in",
            "Ashwamedh stage",
            "ashwamedh2020@gmail.com",
            "MOKSHA",
            "improverse",
            "The Ultimate Improv-Showdown.",
            "1. Team Size Requirement: Teams should consist of 2 to 5 members. \n\n2. Duration Specification: Presentations are expected to last between 5 to 7 minutes.\n\n3. On-the-Spot Situations: Participants will receive situational prompts on the spot as part of the competition.\n\n4. Pre-Registration Requirement: All teams must complete the pre-registration process before the designated deadline which is 29th Feb, 2024. \n\n5. Language Etiquette: Participants are strictly prohibited from using abusive language during the presentation. \n\nThe verdict of the judges shall be deemed conclusive and is not subject to further inquiry or challenge.\n\n",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1jK4Ui7kfM03bA_1dRVQyzKNx5Blw8bNJ.png",
            "sharil",
            "98183 82829",
            "jayashree",
            "98689 78294",
            "College Name, Team Name, Team Size, Team Leader Name, Team Leader Contact, Team Leader Roll No., Member 2 Name, Member 2 Roll No.,Member 3 Name*, Member 3 Roll No.*, Member 4 Name*, Member 4 Roll No*, Member 5 Name*, Member 5 Roll No*\n\n\n\n",
            "Theatre "
        ],
        [
            "vaishali.sharma.ug21@nsut.ac.in",
            "Ashwamedh stage",
            "ashwamedhstage2020@gmail.com",
            "MOKSHA",
            "Moksha film festival",
            "A celebration of Storytelling excellence",
            " Rules:\n1. The theme as well as the genre of the short-film is not imposed. \n\n2. The duration of the film should be between 7 to 12 minutes of time, inclusive of credits.\n\n3. The film should be suitable for all brackets of audience, it should be devoid of any obscenity and nudity. \n\n4. Films which are NOT shot in Hindi or English should be accompanied with subtitles. \n\n\n",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1jIr3Pr6o402aw72tXJxhzw-WSYmCshvA.png",
            "palkin",
            " 92051 49528",
            "chaitanya",
            "99684 53750",
            "College Name, Team Name, Short-Film Name, POC 1 Name, POC 1 Contact, POC 2 name, POC 2 Contact, [Team Details (Name, Role in film, Contact, Email)]\n\n\n\n\n\n\n",
            "Dance "
        ],
        [
            "ananya.sharma.ug21@nsut.ac.in",
            "Mudrakala",
            "ananya.sharma.ug21@nsut.ac.in",
            "MOKSHA",
            "Dharaa",
            "नृत्य की धार - धरा  ...where the flow of dance begins",
            "1)Eligibility: Participants must be college students and participation is open to students from any academic year and branch. Physical college ID proof is mandatory on the day of the event, absence of which may lead to disqualification.\n\n2)Registrations: The event will NOT entertain spontaneous registrations. Early registration opens ahead of the competition.\n\n3)Solo or Duo Performances: The competition is limited to solo or duo performances. One participant/duo will only be allowed to give one performance.\n\n4)Performance Styles: Only classical dance forms are allowed for competition, in line with the spirit of the competition. Western dance styles or dance forms are strictly prohibited.\n\n5)Song Restrictions: Any song/music containing explicit wordings of sexuality or abuse will be disqualified. Participants are encouraged to perform to traditional classical or traditionally inclined fusion music. Classical Bollywood music and fusion is allowed.\n\n6)Time Limit: 2min- 4min (including stage set up for props, etc.). In case the participants exceed the time limit, the judges will feel free to disqualify the participant.\n\n7)Music: Participants have to submit the track in the form and bring it in a pen drive too in mp3 format.\n\n8)Costumes and Accessories: Participants are responsible for arranging their own costumes, jewellery, and music requirements, with an emphasis on traditional and culturally significant attire. No western or revealing clothing will be accepted.\n\n9)Props: Any kind of fluid, flame, powders, heavy or sharp objects are strictly prohibited. Participants need to specify beforehand if they will be using any kind of prop.\n\n10)Position Holders: The top three performances of the competition will be recognised as position holders, with award/cash price for 1st, 2nd, and 3rd places. The decision of the judges and the organising team will be final and binding.\n\n11)Originality and Plagiarism: Any form of plagiarism or copying of choreography, music, or elements from other performances will not be tolerated. The competition values originality and creativity and expects participants to respect the uniqueness of each performance.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1lg-qOVoYdybfESL0V1eI7RhfDZ-DBxmd.png",
            "Lalit Panghal",
            "8178634241",
            "Aman Kumar",
            "9625653418",
            "Name, College, Contact Number, Contact Email Id, Music/Song for Performance(share the drive link and provide access), Upload your college ID (upload drive link and provide access).",
            "Dance "
        ],
        [
            "ananya.sharma.ug21@nsut.ac.in",
            "Mudrakala",
            "ananya.sharma.ug21@nsut.ac.in",
            "MOKSHA",
            "Mudra Munch",
            "\"Sanskriti ki Mudra, Nritya ka Munch\"",
            "1)Eligibility: Participants must be college students and participation is open to students from any academic year and branch. Physical college ID proof is mandatory on the day of the event, absence of which may lead to disqualification.\n\n2)Registrations: The event will NOT entertain spontaneous registrations. Early registration opens ahead of the competition.\n\n3)Group Performances: The competition is limited to group performances. Only one team from a college will be allowed to participate. One team will only be allowed to give one performance.\n\n4)Performance Styles: Only classical dance forms are allowed for competition, in line with the spirit of the competition. Western dance styles or dance forms are strictly prohibited.\n\n5)Song Restrictions: Any song/music containing explicit wordings of sexuality or abuse will be disqualified. Teams are required to perform to traditional classical or traditionally inclined fusion music. Western or party Bollywood music is strictly prohibited.\n\n6)Time Limit: 4min- 6min. In case the team exceeds the time limit, the judges will feel free to disqualify the participating team.\n\n7)Music: Teams have to submit the track in the form and bring it in a pen drive too in mp3 format.\n\n8)Costumes and Accessories: Teams are responsible for arranging their own costumes, jewellery, and music requirements, with an emphasis on traditional and culturally significant attire. No western or revealing clothing will be accepted.\n\n9)Props: Any kind of fluid, flame, powders, heavy or sharp objects are strictly prohibited. Participants need to specify beforehand if they will be using any kind of prop.\n\n10)Position Holders: The top three performances of the competition will be recognised as position holders, with award/cash price for 1st, 2nd, and 3rd places. The decision of the judges and the organising team will be final and binding.\n\n11)Originality and Plagiarism: Any form of plagiarism or copying of choreography, music, or elements from other performances will not be tolerated. The competition values originality and creativity and expects participants to respect the uniqueness of each performance.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/17DAOX9tm6Ero7d2InuZ1UjMuHVqlM5OF.png",
            "Ananya A. Sharma",
            "8800995718",
            "Aaryan Mahajan",
            "9810381171",
            "Team Name, Team Leader, Team Leader Contact Number, College Name, Contact Email Id, List of Performing Members, Music/Song for the Prelims Performance( share the drive link and provide access), Music/Song for the Final Performance( share the drive link and provide access).",
            "Innovision "
        ],
        [
            "ashishupadhyay93155@gmail.com",
            "Google Developer Student Clubs",
            "gdsc.nsut@gmail.com",
            "INNOVISION",
            "Zero Day Apocalypse",
            "Stop the AI Before Dawn",
            "Rules :\n1)Team size :1-2\n2)Duration:-20min per team\n3)No use abusive language in prompt\n4)No outside assistance from any platform/individual during the competition timings.\n5)Number of attempts per level will be fixed \n6)Laptops are not compulsory but are recommended",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1X_hh9kbcv3cJX9euz0OApGw2g46mOlub.png",
            "Prasann",
            "6201782948",
            "Naman Bansal",
            "9810375454",
            "Team Name, Team Size (1 or 2), Team Leader Name, Team Leader Mobile Number, Second Team Member Name*, Second Team Member Mobile Number*",
            "Innovision "
        ],
        [
            "ashishupadhyay93155@gmail.com",
            "Google Developer Student Clubs",
            "gdsc.nsut@gmail.com",
            "INNOVISION",
            "Code Conundrum 2024",
            "Let the coding battle begin!",
            "1.Fixed contest duration of 2 hours.\n2.A set of algorithmic problems will be provided to participants at the beginning of the contest. These problems will vary in difficulty and cover diverse topics.\n 3.Participants are required to utilize their personal laptops equipped with pre-installed development environments, compilers, and text editors.\n4.Winners will be determined based on the highest total score, with tiebreakers considering the time taken for solutions. \n5.A dynamic scoreboard will display participants' real-time scores.\n6.Communication between participants, accessing external resources, or any disruptive behavior is prohibited.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1UQYzgU7bB5-w1_uQrOgjTrJwQu3kk_nw.png",
            "Rishabh Sharma",
            "9868487362",
            "Yash Vats",
            "8506930976",
            "Name, Contact Number, College Name, Year",
            "Innovision "
        ],
        [
            "ashish.upadhyay.ug22@nsut.ac.in",
            "Google Developer Student Clubs, NSUT",
            "gdsc.nsut@gmail.com",
            "INNOVISION",
            "LingoQuest",
            "The Documentation Odyssey",
            "1.The teams will be provided with a programming language with a custom made documentation.\n2.The teams must find the documentation of the same through the fun challenge and solve simple coding questions using it then.\n3.The documentation will consist of riddles and questions which must be solved in order to be able to code in it properly.\n4.Participants must bring their own devices (mobile/laptop).",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1NOJ-FMUamrLkNay6SK4Q0J-ZrS3C8mok.png",
            "Manas Madan",
            "9599034642",
            "Arunima Banerjee ",
            "9811026631",
            "Team Name, Number of Members, Team Leader Name, Team Leader Email Id, Member 1 Name, Member 1 Contact Number, Member 2 Name*, Member 2 Contact Number*",
            "Lifestyle "
        ],
        [
            "aarush.tripathi.bba21@nsut.ac.in",
            "INTAGLIOS ",
            "intagliosthe@gmail.com ",
            "MOKSHA",
            "Moksha Got Talent ",
            "Why to wait for validation of the rest ?? When you can present your talent in front of the best !! Behold, the charisma and aura of NSUT’s greatest fest Moksha and its esteemed event Moksha Got Talent  ",
            "This event will be conducted in form of a competition between the participants. It comprises of 2 rounds.\nPair of two individuals can be allowed to participate. For eg:- A singer and an instrumentalist.\nIn the first round the participants need to record a video of their art, activity & performance and upload it in the form that will be made available to all. The video shouldn't exceed the time limit of 3 minutes. \nThe deserving participants will be selected and shall qualify for round 2. \nRound 2 will conducted on the day of Moksha fest, at a suitable venue, in front of the judges and an audience.For round 2, every participant needs to give his/her best shot.\nScores will be marked and their performances would be assessed by the judges.\nThe best performer will be crowned as winner.\nWinners will be ranked as per 1st, 2nd and 3rd position(s).",
            "",
            "Mrityunjay Gupta ",
            "93183 10099",
            "Nikhil Kumar ",
            "83779 49111",
            "Email, Your Name, College Name, Your Number, Your Email Id, Your Preferred skill set {Dancing\r\nSinging\r\nRapping\r\nInstrumental Music\r\nOthers},[Drive link of your performance], Why you want to participate in MGT?",
            "Music "
        ],
        [
            "crescendo.nsit@nsitonline.in",
            "Crescendo",
            "crescendo.nsit@nsitonline.in",
            "MOKSHA",
            "Avalanche",
            "The Battle of Bands",
            "RULES AND REGULATIONS FOR THE EVENT:\n\n1. Maximum two teams per institution are allowed to participate in the event.\n2. Each band must have 3-8 members.\n3. Cross college teams are allowed.\n4. Recorded tracks and loops are not allowed in the competition.\n5. Each team will be given 12 minutes for their performance, including sound check and stage setting\n6. A basic 5-piece drum kit along with cymbals, amplifiers, microphones and speaker setup will be provided to the teams\n7. The decision taken by the judges will be considered final and binding\n8. All participants are required to carry valid college ID along with them on the day of the competition.\n\nREGARDING THE PRELIMINARY ONLINE ROUND:\n1. Participants are required to upload a YouTube/google drive link in the registration form given in the website. \n2. Fill the details of the POC in the form below and add the details of the group members in a separate google doc and submit the link in the registration form given in the website\n3. Don't forget to change the access of the google doc\n4. The uploaded file should be of video format",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1qb0gvYpM68rW8fWW3GouOHmHT3Ks-tmD.png",
            "Shrestha Shashank",
            "98711 36375",
            "Arnab",
            "70235 65744",
            "Email\n*\nFull Name (POC)\n*\nContact Number (POC)\n*\nOfficial Email Address (POC)\n*\nCollege Name\n*\nCollege Roll Number (POC)\n*\nCollege ID Card of POC (Upload Scanned Photo)\n*\nGoogle Doc link with details of band members\n*\nPerformance Link\n*",
            "Music "
        ],
        [
            "crescendo.nsit@nsitonline.in",
            "Crescendo",
            "crescendo.nsit@nsitonline.in",
            "MOKSHA",
            "Symphony",
            "Solo instrumental competition",
            "COMPETITION RULES:\n \n1. This is a solo competition. A maximum of 2 accompanists will be allowed per participant.\n2. Time limit is 6+2 minutes, the video submitted should be un-edited.\n3. Participants are required to bring their own instruments.\n4. Accompanist(s) from any college(s) are allowed. However, no accompanist can be a part of more than 1 participating team. In case of violation, all the associated participants will be disqualified.\n5. Pre-recorded backing tracks are not allowed. Live looping is allowed.\n6. There is no limitation on the genre of music to be presented.\n7. Judgment will be based on the qualities like dynamics, expression, phrasing, rhythm, technique, tone quality, etc.\n8. Judge's decision will be final and binding. \n9. All participants are required to bring their college IDs on the day of the event.\n \nREGARDING PRELIMINARY ENTRIES:\n\n1. Entries of a minimum of 3 minutes and a maximum of 7 minutes time.\n2. Upload a YouTube/Google Drive link of their previous performance in the registration form given on the website\n3. Entry can be in audio/video format.\n4. Drums are allowed in the preliminary round only.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1mhzaSq8NhGMPHPOqL3zquJfOcUHQY0Td.png",
            "Nilanchal",
            "93196 79719",
            "Vidyansh",
            "93194 75114",
            "",
            "Music "
        ],
        [
            "crescendo.nsit@nsitonline.in",
            "Crescendo",
            "crescendo.nsit@nsitonline.in",
            "MOKSHA",
            "Trapped",
            "HIP-HOP Event",
            "Trapped:\n\nA) RAP COMPETITION\n\nREGARDING PRELIMINARY ENTRIES:\n\n1. Participants are required to upload their entries in the registration form given on the website through Youtube/Google Drive Link. Time limit for the act is 2mins.\n3. Entry must be strictly in video format.This is a solo event. Entries involving duet or group performances will not be allowed.\n4. Only one entry per person per event is allowed. However, more than one entry from an institute/college is allowed.\n5.  We generally expect you to perform a self-written verse.\n\n\nCOMPETITION RULES:\n\n1) The Final round will be a series of elimination rounds. \n2) Further details of the round will be announced on the spot and hence this round will be spontaneous. The participants will be required to be ready for impromptu performances. \n2) You can use your beat of choice in the background while performing unless specified otherwise. \n\nB) Hip-Hop/ EDM Production\n\nREGARDING PRELIMINARY ENTRIES:\n1. Participants are required to upload their entries of their Original Act in the registration form given on the website through Youtube/Google Drive Link.\n2. Time limit for the act is 3mins.\n3. Entry can be in audio/video format.\n\n\nCOMPETITION RULES:\n\n1. A sample pack containing handpicked samples will be provided. The samples may be completely abstract.\n2. You'll be required to make a track in your style, in a DAW of your preference. You ARE REQUIRED to use AT LEAST 2 SAMPLES FROM THE PACK YOU'VE BEEN PROVIDED.\n3. You are allowed to use your own drum kits, VSTs synths, drum samples, effects and transitions. There is no boundary. The sky is your limit!\n4. The track should be of a minimum of 2 minutes to a maximum of 3 minutes, try to structure it accordingly. Again, make sure you use at least 2 samples from the pack that is provided to you.\n6. Submit the final song (format - mp3) using the Google form provided. (In case of any discrepancy you'll be personally contacted to provide a zip file of your project) \n7. The sample pack has been attached below for your perusal.\n\nSample Pack: https://drive.google.com/drive/folders/1_N3-48BYsrsqDD6lGv6Hlmk2M2s0UERe\n\nC) Beatbox Competition\n\nREGARDING PRELIMINARY ENTRIES:\n\n1. You are required to send in a video of a beatbox routine preferably of a duration of 1-1.5 minutes.\n\nCOMPETITION RULES:\n\n1) This will be an offline round where you will be presenting a routine of 1.5 to 2 minutes. It is up to you if you want to perform a new routine or the same as the one sent for the preliminary round.\n2) The top 4 performers from this round will be chosen for a beatbox battle amongst themselves and out of this set of performers, 2 will be chosen for the final round. A routine of a maximum of 1.5 minutes will be accepted.\n3) In the final round the 2 beatboxers will be coupled with a certain musical instrument (eg. guitar/flute/keyboard) OR a vocalist where they must create an impromptu routine.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1lFhxfshug77HWUVRnGz99vtz_s4d3cH6.png",
            "Aryan kumar",
            "80763 66691",
            "Ravneet singh",
            "99718 77828",
            "",
            "Music "
        ],
        [
            "crescendo.nsit@nsitonline.in",
            "Crescendo",
            "crescendo.nsit@nsitonline.in",
            "MOKSHA",
            "Melody",
            "Western solo singing competition ",
            "Melody: \n\nCOMPETITION RULES:\n\n1. Each participant will be given a total of 4+2 minutes including soundcheck and stage setup time.\n2. The instrumentalists need not necessarily be from the same college.\n3. Instruments required by the accompanists are to be arranged by the participants only.\n4. There is no limitation on the genre of music to be performed.\n5. It has to be an acoustic performance. Pre-recorded music/tracks are not allowed.\n\nREGARDING PRELIMINARY ENTRIES:\n\n1. Participants will be required to upload a google drive link of a video without any processed vocals.\n2. The uploaded file should be strictly in video format only. Audio files will not be accepted\n3. Time limit for this round will be 2 minutes.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1vvqb-8l4J_bR2JbBwaRwnVJoUdJW70B6.png",
            "Jyotshna",
            "73033 54767",
            "Vishnu",
            "90197 73682",
            "",
            "Music "
        ],
        [
            "crescendo.nsit@nsitonline.in",
            "Crescendo",
            "crescendo.nsit@nsitonline.in",
            "MOKSHA",
            "Voice of Moksha",
            "Hindi solo singing competition",
            "COMPETITION RULES:\n\n1. Each participant will be given a total of 4+2 minutes including soundcheck and stage setup time.\n2. In addition to an electronic tanpura, a maximum of 2 accompanists shall be allowed. The instrumentalists need not necessarily be from the same college.\n3. It will be the responsibility of the participant and the accompanying instrumentalists to arrange and maintain the instruments.\n4. Use of synthesizer tracks and pre-recorded tracks is strictly prohibited. Any participant found violating this rule will be liable to immediate disqualification.\n5. Genre must be strictly Bollywood.\n6. A maximum of two entries will be shortlisted per college.\n7. All participants are required to bring their college IDs on the day of the events.\n \nREGARDING PRELIMINARY ENTRIES:\n\n1. Upload a Google Drive link of a recorded piece in the registration form given in the website\n2. The uploaded file should be strictly in video format only.",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1qsu6y9rQTfw1SMt5SAfzg4bLx9AQ7Whr.png",
            "Pranav Arora",
            "9205376809",
            "Arpit Rastogi",
            "70654 15895",
            "",
            "Music "
        ],
        [
            "crescendo.nsit@nsitonline.in",
            "Crescendo",
            "crescendo.nsit@nsitonline.in",
            "MOKSHA",
            "Harmony",
            "The Acapella competition",
            "RULES AND REGULATIONS:\n\n1.Each institution is allowed to send only one entry from their college\n2.A minimum of 5 and a maximum of 25 members (inclusive of the conductor) are allowed for each entry.\n3. This is an Acapella competition. This implies no instruments are allowed in the event.\n4. Each team will be given 12 minutes for their performance, including sound check and stage setting.\n5. No pre recorded tracks are allowed in this competition, and the videos should be raw. No editing will be allowed.\n6. There is no restriction of genre for this event. Participants are free to perform the genre of their choice.\n7. All participants are required to bring valid college ID cards on the day of the competition.\n\nREGARDING PRELIMINARY ENTRIES:\n\n1. Participants are required to upload a YouTube/google drive link in the registration form given on the website\n2. The uploaded file can be of only video format",
            "https://mokshainnovision.s3.eu-north-1.amazonaws.com/events/1WgqUMp4DAeYgbpdpbbp7wlyIO9z_D513.png",
            "Akhil",
            "95603 74139",
            "Shreyashi",
            "99714 30750",
            "",
            null
        ]
    ]
